///////////////
// Constants //
///////////////

// Asset Constants
ASSET_RENDER_MODE_2D = 0;
ASSET_RENDER_MODE_ISOMETRIC = 1;

// Persist Constants
PERSIST_DISABLED = false;
PERSIST_ENABLED = true;

// Locale Constants
LOCALE_EVERYWHERE = 0;
LOCALE_ALL_CLIENTS = 1;
LOCALE_SINGLE_CLIENT = 2;
LOCALE_SERVER_ONLY = 4;
LOCALE_RESERVED1 = 8;
LOCALE_RESERVED2 = 16;
LOCALE_RESERVED3 = 32;
LOCALE_DB = 64;

LOCALE_DEFAULT = LOCALE_EVERYWHERE; // Set the default locale setting when none is supplied

// Entity Constants
ENTITY_TYPE_BACKGROUND = 0;
ENTITY_TYPE_TILE = 1;
ENTITY_TYPE_OBJECT = 2;
ENTITY_TYPE_SPRITE = 3;
ENTITY_TYPE_UI = 4;

ENTITY_TB_NOBLOCK_NOCHECK = 0;
ENTITY_TB_NOBLOCK_CHECK = 1;
ENTITY_TB_BLOCK_NOCHECK = 2;
ENTITY_TB_BLOCK_CHECK = 3;

NET_MODE_FIXED_MOTION = 0;
NET_MODE_FREE_MOTION = 1;

// Layer Constants
LAYER_BACKGROUNDS = 0;
LAYER_TILES = 1;
LAYER_OBJECTS = 2;
LAYER_SPRITES = 2;
LAYER_UI = 3;

LAYER_AUTO_NONE = 0;
LAYER_AUTO_CULL = 1;
LAYER_AUTO_REQUEST = 2;

LAYER_TYPE_CANVAS = 0;
LAYER_TYPE_HTML = 1;
LAYER_TYPE_WEBGL = 2;
LAYER_TYPE_AUTO = 3;

// Map Constants
MAP_RENDER_MODE_2D = 0;
MAP_RENDER_MODE_ISOMETRIC = 1;

MAP_NO_DIRTY = 0;
MAP_USE_DIRTY = 1;
MAP_DEBUG_DIRTY = 2;
MAP_DEBUG_ENTITIES = 4;

MAP_TYPE_FLAT = 0;
MAP_TYPE_POINTS = 1;

// Direction Constants
DIRECTION_NONE = 0;
DIRECTION_N = 1;
DIRECTION_E = 2;
DIRECTION_S = 4;
DIRECTION_W = 8;
DIRECTION_NE = 3;
DIRECTION_SE = 6;
DIRECTION_NW = 9;
DIRECTION_SW = 12;

// Propagate Constants
PROPAGATE_CREATE = 1;
PROPAGATE_UPDATE = 2;
PROPAGATE_DELETE = 3;

// Path Constants
PATH_TYPE_ENTITY = 0;
PATH_TYPE_CAMERA = 1;

// Internal Engine Constants
CLEAN_MOVE_DIR_NONE = 0;
CLEAN_MOVE_DIR_LEFT = 1;
CLEAN_MOVE_DIR_RIGHT = 2;
CLEAN_MOVE_DIR_UP = 3;
CLEAN_MOVE_DIR_DOWN = 4;

// Tile corner points
TILE_CORNER_1 = 0
TILE_CORNER_2 = 1
TILE_CORNER_3 = 2
TILE_CORNER_4 = 3

// Sound type constants
SOUND_TYPE_PLAYLIST = 1;
SOUND_TYPE_TRACK = 2;
SOUND_TYPE_EFFECT = 3;